-- Active: 1736634064306@@127.0.0.1@3306@mercado_vinicius
#criar base da dados
CREATE DATABASE HortFruit;

#criar tabelas

CREATE TABLE IF NOT EXISTS cliente(
	cod INT NOT NULL,
	cpf VARCHAR(11) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	endereco VARCHAR(100) NOT NULL,
	telefone VARCHAR(11) NOT NULL,
	pontos INT DEFAULT 0,
	data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
	data_modificacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	UNIQUE(cpf),
	PRIMARY KEY (cod)
) ;
CREATE TABLE IF NOT EXISTS categoria(
	cod INT NOT NULL,
	nome VARCHAR(20) NOT NULL,
	tipo VARCHAR(20) NOT NULL,
	data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
	data_modificacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY (cod)
);

CREATE TABLE IF NOT EXISTS produto(
	cod INT NOT NULL,
	cod_categoria INT NOT NULL,
	nome VARCHAR(30) NOT NULL,
	quant INT NOT NULL,
	valor_unitario DECIMAL(5,2) NOT NULL,
	data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
	data_modificacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (cod_categoria) REFERENCES categoria(cod),
	UNIQUE(nome),
	PRIMARY KEY (cod)
);

-- Tabela que registra as alterações de preço
CREATE TABLE IF NOT EXISTS historico_preco (
	cod INT NOT NULL,
	cod_produto INT NOT NULL,
	preco DECIMAL(5,2) NOT NULL,
	data_inicio DATETIME,
	data_fim DATETIME,

	PRIMARY KEY (cod),
	FOREIGN KEY (cod_produto) REFERENCES produto (cod)
);



CREATE TABLE IF NOT EXISTS colaborador(
	cod INT NOT NULL,
 	cpf VARCHAR(11) NOT NULL,
	nome VARCHAR(255) NOT NULL,
	data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,

	data_modificacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (cod),
	UNIQUE(cpf)
);

CREATE TABLE IF NOT EXISTS gerente(
	cod INT NOT NULL,
	cod_colaborador INT NOT NULL,
	data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
	data_modificacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY (cod),
	FOREIGN KEY (cod_colaborador) REFERENCES colaborador(cod)
);

CREATE TABLE IF NOT EXISTS subordinado(
	cod INT NOT NULL,
	cod_colaborador INT NOT NULL,
	cod_gerente INT NOT NULL,
	data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
	data_modificacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY (cod),
	FOREIGN KEY (cod_colaborador) REFERENCES colaborador(cod),
	FOREIGN KEY (cod_gerente) REFERENCES gerente(cod)
);


CREATE TABLE IF NOT EXISTS venda(
	cod INT NOT NULL,
	cod_colaborador INT NOT NULL,
	cod_cliente INT NOT NULL,
	total DECIMAL(20, 2),
	data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
	data_modificacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY(cod),
	FOREIGN KEY (cod_colaborador) REFERENCES colaborador(cod),
	FOREIGN KEY (cod_cliente) REFERENCES cliente(cod)
);

CREATE TABLE IF NOT EXISTS venda_produto(
	cod INT NOT NULL,
	cod_venda INT NOT NULL,
	cod_produto INT NOT NULL,
	quant INT NOT NULL,
	valor_unitario DECIMAL(5,2),
	valor DECIMAL(10,2),
	data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
	data_modificacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY(cod),
	FOREIGN KEY (cod_venda) REFERENCES venda(cod),
	FOREIGN KEY (cod_produto) REFERENCES produto(cod)
);

CREATE TABLE IF NOT EXISTS fornecedor(
	cod INT NOT NULL,
	cnpj VARCHAR(14) NOT NULL UNIQUE,
	nome VARCHAR(255) NOT NULL,
	endereco VARCHAR(255) NOT NULL, 
	telefone VARCHAR(11) NOT NULL,
	data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
	data_modificacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY(cod)
);

CREATE TABLE IF NOT EXISTS lista(
	cod INT NOT NULL,
	cod_gerente INT NOT NULL,
	data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
	data_modificacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY(cod),
	FOREIGN KEY (cod_gerente) REFERENCES gerente(cod)
);

CREATE TABLE IF NOT EXISTS lista_produto(
	cod INT NOT NULL,
	cod_lista INT NOT NULL,
	cod_produto INT NOT NULL,
	quant INT NOT NULL,
	data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
	data_modificacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY(cod),
	FOREIGN KEY (cod_lista) REFERENCES lista(cod),
	FOREIGN KEY (cod_produto) REFERENCES produto(cod)
);

CREATE TABLE IF NOT EXISTS lista_fornecedor(
	cod INT NOT NULL,
	cod_lista INT NOT NULL,
	cod_fornecedor INT NOT NULL,
	data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
	data_modificacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY(cod),
	FOREIGN KEY (cod_lista) REFERENCES lista(cod),
	FOREIGN KEY (cod_fornecedor) REFERENCES fornecedor(cod)
);

CREATE TABLE IF NOT EXISTS orcamento(
	cod INT NOT NULL,
	cod_fornecedor INT NOT NULL,
	total DECIMAL(30, 2),
	foi_aprovado BOOLEAN DEFAULT FALSE,
	data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
	data_modificacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY(cod),
	FOREIGN KEY (cod_fornecedor) REFERENCES fornecedor(cod)
);

CREATE TABLE IF NOT EXISTS orcamento_produto(
	cod INT NOT NULL,
	cod_orcamento INT NOT NULL,
	cod_produto INT NOT NULL,
	quant INT NOT NULL,
	valor_custo_unitario DECIMAL(5,2) NOT NULL,
	valor_custo_total DECIMAL(20, 2),
	data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
	data_modificacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY(cod),
	FOREIGN KEY (cod_orcamento) REFERENCES orcamento(cod),
	FOREIGN KEY (cod_produto) REFERENCES produto(cod)
);

CREATE TABLE IF NOT EXISTS lista_orcamento (
	cod INT NOT NULL,
	cod_lista INT NOT NULL,
	cod_orcamento INT NOT NULL,
	data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
	data_modificacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY(cod),
	FOREIGN KEY (cod_lista) REFERENCES lista(cod),
	FOREIGN KEY (cod_orcamento) REFERENCES orcamento(cod)
);